import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
async function client(username){let cookie='';async function call(path,method='GET',data){const r=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(data&&!(data instanceof FormData)?{'Content-Type':'application/json'}:{})},body:data?(data instanceof FormData?data:JSON.stringify(data)):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,...await r.json()}}if(username)assert.equal((await call('/api/login','POST',{username,password:'demo1234'})).status,200);return call}
const master=await client('masteradmin'),player=await client('jugador01'),cashier=await client('cajero01'),guest=await client();
const initial=(await master('/api/site')).settings;assert.equal((await guest('/api/site','PUT',initial)).status,401);assert.equal((await player('/api/site','PUT',initial)).status,403);assert.equal((await cashier('/api/site','PUT',initial)).status,403);
const fd=new FormData();fd.set('title','Test');fd.set('category','all');fd.set('image',new Blob([Buffer.from('89504e470d0a1a0a','hex')],{type:'image/png'}),'test.png');let uploaded=await master('/api/banners','POST',fd);assert.equal(uploaded.status,200);assert((await guest('/api/site')).banners.some(b=>b.id===uploaded.id));assert.equal((await master('/api/banners/'+uploaded.id,'PATCH',{active:false,position:2})).status,200);assert(!(await guest('/api/site')).banners.some(b=>b.id===uploaded.id));await master('/api/banners/'+uploaded.id,'DELETE');
assert.equal((await master('/api/site','PUT',{...initial,maintenance:true})).status,200);assert.equal((await guest('/api/site')).settings.maintenance,true);await master('/api/site','PUT',initial);
assert.equal((await cashier('/api/users','POST',{username:'invalidstaff',password:'test1234',full_name:'Test',role:'agent'})).status,403);
const users=(await master('/api/users')).users,id=users.find(u=>u.username==='jugador01').id;const before=(await player('/api/session')).user.balance;assert.equal((await master('/api/wallet/transfer','POST',{userId:id,action:'credit',amount:100})).balance,before+100);assert.equal((await master('/api/wallet/transfer','POST',{userId:id,action:'debit',amount:100})).balance,before);assert.equal((await master('/api/wallet/transfer','POST',{userId:id,action:'debit',amount:1000000000})).status,400);assert.equal((await player('/api/wallet/transfer','POST',{userId:id,action:'credit',amount:1})).status,403);assert.equal((await player('/api/demo/game','POST',{bet:1})).status,404);console.log('PASS: banners, publishing, settings, maintenance, roles, balance and ledger, insufficient balance, removed demo game.');
