import express from 'express';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import multer from 'multer';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import helmet from 'helmet';
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);const app=express();const PORT=process.env.PORT||3000;
const dataDir=process.env.DATA_DIR||path.join(__dirname,'data');fs.mkdirSync(dataDir,{recursive:true});const db=new Database(path.join(dataDir,'universe.db'));db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('master','agent','player','cashier')),full_name TEXT NOT NULL,email TEXT DEFAULT '',balance INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,avatar_data TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,actor_id INTEGER,kind TEXT NOT NULL CHECK(kind IN ('credit','debit','adjustment')),amount INTEGER NOT NULL,note TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));CREATE INDEX IF NOT EXISTS idx_ledger_user ON ledger(user_id);`);
if(!db.prepare('SELECT COUNT(*) c FROM users').get().c){const i=db.prepare('INSERT INTO users(username,password_hash,role,full_name,email,balance) VALUES(?,?,?,?,?,?)');i.run('masteradmin',bcrypt.hashSync('demo1234',10),'master','Universe Master','master@universe.demo',0);i.run('agente01',bcrypt.hashSync('demo1234',10),'agent','Agente Demo','agent@universe.demo',250000);i.run('jugador01',bcrypt.hashSync('demo1234',10),'player','Jugador Demo','player@universe.demo',50000);i.run('cajero01',bcrypt.hashSync('demo1234',10),'cashier','Cajero Demo','cashier@universe.demo',100000);}
app.use(helmet({contentSecurityPolicy:false}));app.use((q,s,n)=>{if(['POST','PUT','PATCH','DELETE'].includes(q.method)&&q.headers['sec-fetch-site']==='cross-site')return s.status(403).json({error:'Solicitud de otro sitio rechazada.'});n();});app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true,limit:'3mb'}));app.use(session({secret:process.env.SESSION_SECRET||'prisma-demo-session',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:false,maxAge:28800000}}));// Gate HTML before static delivery; staff may preview the player lobby.
app.use((req,res,next)=>{
 if(!['/player.html','/master.html'].includes(req.path))return next();
 const u=currentUser(req);
 if(!u||!u.active)return res.redirect('/');
 if(req.path==='/master.html'&&u.role==='player')return res.redirect('/player.html');
 next();
});
app.use(express.static(path.join(__dirname,'public')));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:1536000},fileFilter:(_r,f,cb)=>cb(null,/^image\/(png|jpe?g|webp|gif)$/i.test(f.mimetype))});
const currentUser=req=>req.session.userId?db.prepare('SELECT id,username,role,full_name,email,balance,active,avatar_data,created_at FROM users WHERE id=?').get(req.session.userId):null;const auth=(req,res,next)=>{const u=currentUser(req);if(!u||!u.active)return res.status(401).json({error:'No autenticado.'});req.user=u;next()};const staff=(req,res,next)=>auth(req,res,()=>['master','agent','cashier'].includes(req.user.role)?next():res.status(403).json({error:'Sin permisos.'}));const amount=v=>{const n=Number(v);if(!Number.isInteger(n)||n<=0||n>1000000000)throw Error('Monto inválido.');return n};
app.get('/api/health',(_q,s)=>s.json({ok:true,service:'prisma-virtual-casino'}));app.get('/api/session',(q,s)=>s.json({user:currentUser(q)?.active?currentUser(q):null}));
app.post('/api/login',(q,s)=>{const {username='',password=''}=q.body||{};const u=db.prepare('SELECT * FROM users WHERE username=?').get(String(username).trim());if(!u||!u.active||!bcrypt.compareSync(String(password),u.password_hash))return s.status(401).json({error:'Usuario o contraseña incorrectos.'});q.session.regenerate(err=>{if(err)return s.status(500).json({error:'No se pudo iniciar la sesión.'});q.session.userId=u.id;s.json({ok:true,redirect:u.role==='player'?'/player.html':'/master.html',user:currentUser(q)});});});app.post('/api/logout',(q,s)=>q.session.destroy(()=>s.json({ok:true})));
app.get('/api/stats',staff,(q,s)=>{const players=db.prepare("SELECT COUNT(*) c FROM users WHERE role='player'").get().c;const agents=db.prepare("SELECT COUNT(*) c FROM users WHERE role='agent'").get().c;const cashiers=db.prepare("SELECT COUNT(*) c FROM users WHERE role='cashier'").get().c;const active=db.prepare("SELECT COUNT(*) c FROM users WHERE active=1 AND role IN ('player','agent','cashier')").get().c;const volume=db.prepare("SELECT COALESCE(SUM(CASE WHEN kind='credit' THEN amount WHEN kind='debit' THEN -amount ELSE 0 END),0) v FROM ledger").get().v;s.json({players,agents,cashiers,active,ledgerVolume:volume});});
app.get('/api/users',staff,(q,s)=>s.json({users:db.prepare("SELECT id,username,role,full_name,email,balance,active,avatar_data,created_at FROM users WHERE role!='master' ORDER BY id DESC").all()}));
app.post('/api/users',staff,upload.single('avatar'),(q,s)=>{const {username,password,role='player',full_name,email=''}=q.body;if(q.user.role!=='master'&&role!=='player')return s.status(403).json({error:'Solo administración puede crear personal.'});if(!['player','agent','cashier'].includes(role))return s.status(400).json({error:'Rol inválido.'});if(!username||!password||!full_name)return s.status(400).json({error:'Completá usuario, contraseña y nombre.'});try{const avatar=q.file?`data:${q.file.mimetype};base64,${q.file.buffer.toString('base64')}`:'';const x=db.prepare('INSERT INTO users(username,password_hash,role,full_name,email,avatar_data) VALUES(?,?,?,?,?,?)').run(String(username).trim(),bcrypt.hashSync(String(password),10),role,String(full_name).trim(),String(email).trim(),avatar);s.json({ok:true,id:x.lastInsertRowid});}catch(e){s.status(400).json({error:e.message.includes('UNIQUE')?'Ese usuario ya existe.':'No se pudo crear el usuario.'});}});
app.patch('/api/users/:id',staff,upload.single('avatar'),(q,s)=>{const id=Number(q.params.id),t=db.prepare('SELECT * FROM users WHERE id=?').get(id);if(t&&(t.role==='master'||(q.user.role!=='master'&&t.role!=='player')))return s.status(403).json({error:'Sin permisos.'});if(!t)return s.status(404).json({error:'Usuario no encontrado.'});const active=q.body.active==null?t.active:(q.body.active==='true'||q.body.active==='1'?1:0);const avatar=q.file?`data:${q.file.mimetype};base64,${q.file.buffer.toString('base64')}`:t.avatar_data;db.prepare('UPDATE users SET full_name=?,email=?,active=?,avatar_data=? WHERE id=?').run(q.body.full_name??t.full_name,q.body.email??t.email,active,avatar,id);s.json({ok:true});});
app.post('/api/wallet/transfer',staff,(q,s)=>{try{const userId=Number(q.body.userId),a=amount(q.body.amount),action=q.body.action,t=db.prepare('SELECT id,balance,active,role FROM users WHERE id=?').get(userId);if(t&&(t.role==='master'||(q.user.role!=='master'&&t.role!=='player')))return s.status(403).json({error:'Sin permisos.'});if(!t||!t.active)return s.status(404).json({error:'Usuario no encontrado o inactivo.'});if(!['credit','debit'].includes(action))return s.status(400).json({error:'Movimiento inválido.'});const next=db.transaction(()=>{const nb=t.balance+(action==='credit'?a:-a);if(nb<0)throw Error('Saldo insuficiente para retirar esa cantidad.');db.prepare('UPDATE users SET balance=? WHERE id=?').run(nb,userId);db.prepare('INSERT INTO ledger(user_id,actor_id,kind,amount,note) VALUES(?,?,?,?,?)').run(userId,q.user.id,action,a,String(q.body.note|| (action==='credit'?'Carga de fichas':'Retiro de fichas')));return nb;})();s.json({ok:true,balance:next});}catch(e){s.status(400).json({error:e.message});}});
app.get('/api/ledger',staff,(q,s)=>s.json({ledger:db.prepare('SELECT l.id,l.kind,l.amount,l.note,l.created_at,u.username,u.full_name FROM ledger l JOIN users u ON u.id=l.user_id ORDER BY l.id DESC LIMIT 100').all()}));app.get('/api/me/ledger',auth,(q,s)=>s.json({ledger:db.prepare('SELECT id,kind,amount,note,created_at FROM ledger WHERE user_id=? ORDER BY id DESC LIMIT 50').all(q.user.id)}));
// Persistent presentation settings; the existing users and ledger are preserved.
db.exec(`CREATE TABLE IF NOT EXISTS site_settings(id INTEGER PRIMARY KEY CHECK(id=1),content TEXT NOT NULL); CREATE TABLE IF NOT EXISTS banners(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,subtitle TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT 'all',image TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,position INTEGER NOT NULL DEFAULT 0);`);
const defaults={name:'NEXORA',tagline:'Elegí tu mundo. Descubrí una experiencia llena de color y nuevas posibilidades.',accent:'#beff58',maintenance:false,categories:{casino:true,live:true,sports:true},announcement:'Un universo de entretenimiento. Todos los saldos son virtuales.'};
db.prepare('INSERT OR IGNORE INTO site_settings(id,content) VALUES(1,?)').run(JSON.stringify(defaults));
const settings=()=>JSON.parse(db.prepare('SELECT content FROM site_settings WHERE id=1').get().content);
const master=(q,s,n)=>auth(q,s,()=>q.user.role==='master'?n():s.status(403).json({error:'Solo administración puede modificar el sitio.'}));
app.get('/api/site',(_q,s)=>s.json({settings:settings(),banners:db.prepare('SELECT * FROM banners WHERE active=1 ORDER BY position,id DESC').all()}));
app.put('/api/site',master,(q,s)=>{const b=q.body;if(typeof b.name!=='string'||!b.name.trim()||b.name.length>24||!/^#[0-9a-f]{6}$/i.test(b.accent||'')||typeof b.maintenance!=='boolean'||!['casino','live','sports'].every(k=>typeof b.categories?.[k]==='boolean'))return s.status(400).json({error:'Revisá nombre, color y categorías.'});const v={name:b.name.trim(),tagline:String(b.tagline||'').slice(0,100),announcement:String(b.announcement||'').slice(0,200),accent:b.accent,maintenance:b.maintenance,categories:b.categories};db.prepare('UPDATE site_settings SET content=? WHERE id=1').run(JSON.stringify(v));s.json({ok:true,settings:v});});
app.get('/api/banners',master,(_q,s)=>s.json({banners:db.prepare('SELECT * FROM banners ORDER BY position,id DESC').all()}));
function validImage(f){if(!f)return false;const b=f.buffer;return (f.mimetype==='image/png'&&b.subarray(0,8).toString('hex')==='89504e470d0a1a0a')||(f.mimetype==='image/jpeg'&&b[0]===255&&b[1]===216&&b[2]===255)||(f.mimetype==='image/webp'&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')||(f.mimetype==='image/gif'&&/^GIF8[79]a/.test(b.toString('ascii',0,6)));}
app.post('/api/banners',master,upload.single('image'),(q,s)=>{const {title='',subtitle='',category='all',position='0'}=q.body;if(!title.trim()||title.length>80||!['all','casino','live','sports'].includes(category)||!Number.isInteger(Number(position))||!validImage(q.file))return s.status(400).json({error:'Ingresá un título y una imagen PNG, JPG, WEBP o GIF válida (hasta 1,5 MB).'});const image=`data:${q.file.mimetype};base64,${q.file.buffer.toString('base64')}`;const r=db.prepare('INSERT INTO banners(title,subtitle,category,position,image) VALUES(?,?,?,?,?)').run(title.trim(),String(subtitle).slice(0,160),category,Number(position),image);s.json({ok:true,id:r.lastInsertRowid});});
app.patch('/api/banners/:id',master,(q,s)=>{if(typeof q.body.active!=='boolean'||!Number.isInteger(Number(q.body.position)))return s.status(400).json({error:'Estado u orden inválido.'});const r=db.prepare('UPDATE banners SET active=?,position=? WHERE id=?').run(q.body.active?1:0,Number(q.body.position),q.params.id);s.status(r.changes?200:404).json(r.changes?{ok:true}:{error:'Banner no encontrado.'});});
app.delete('/api/banners/:id',master,(q,s)=>{const r=db.prepare('DELETE FROM banners WHERE id=?').run(q.params.id);s.status(r.changes?200:404).json(r.changes?{ok:true}:{error:'Banner no encontrado.'});});
app.use((err,_q,s,_n)=>{console.error(err.message);s.status(err.code==='LIMIT_FILE_SIZE'?413:400).json({error:err.code==='LIMIT_FILE_SIZE'?'La imagen supera 1,5 MB.':'No se pudo procesar la solicitud.'});});

app.use((q,s,n)=>q.path.startsWith('/api/')?s.status(404).json({error:'Ruta API no encontrada.'}):s.sendFile(path.join(__dirname,'public','index.html'),e=>e&&n(e)));app.listen(PORT,'0.0.0.0',()=>console.log(`Prisma running on ${PORT}`));

