import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'bravo-test-')),port=process.env.TEST_PORT||'3100',base='http://127.0.0.1:'+port;
const env={...process.env,DEMO_MODE:'true',NODE_ENV:'test',DATA_DIR:data,PORT:port};
let seeded=spawnSync(process.execPath,['scripts/seed-demo.mjs'],{cwd:root,env,encoding:'utf8'});assert.equal(seeded.status,0,seeded.stderr);
const before=fs.readFileSync(path.join(data,'universe.db'));assert.equal(spawnSync(process.execPath,['scripts/seed-demo.mjs'],{cwd:root,env}).status,0);assert.deepEqual(fs.readFileSync(path.join(data,'universe.db')),before,'Seeder must never overwrite an existing DB');
const server=spawn(process.execPath,['scripts/start-demo.mjs'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let logs='';server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
let browser;
try{
 for(let i=0;i<60;i++){try{await fetch(base+'/api/health');break}catch{await new Promise(r=>setTimeout(r,100))}}
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const player={username:'demo_jugador',password:'BravoJuega!26'},admin={username:'demo_admin',password:'BravoPanel!26'};
 const output=process.env.EVIDENCE_DIR||path.join(os.tmpdir(),'bravo-evidence');fs.mkdirSync(output,{recursive:true});
 async function shot(name,fullPage=false){await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(150);await page.screenshot({path:path.join(output,name+'.png'),fullPage})}
 async function noOverflow(){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Horizontal overflow on '+page.url())}
 async function login(user,target){await page.goto(base+'/');await page.locator('#accessForm').waitFor();await page.locator('#username').fill(user.username);await page.locator('#password').fill(user.password);await page.locator('#submitAccess').click();await page.waitForURL(base+target)}
 async function json(url,method='get',data){const r=await page.request[method](base+url,data?{data}:{});return {status:r.status(),body:await r.json()}}
 for(const route of ['/','/index.html','/login','/login.html']){await page.goto(base+route);await page.locator('#accessForm').waitFor();assert.equal(await page.locator('#lobbyContent').count(),0)}
 for(const route of ['/casino','/player.html','/admin','/master.html','/preview']){await page.goto(base+route);assert.equal(new URL(page.url()).pathname,'/login')}
 assert.equal((await page.request.get(base+'/%70layer.html',{maxRedirects:0})).status(),404);
 await page.goto(base+'/');await shot('login-desktop');
 await page.locator('#username').fill('demo_admin');await page.locator('#password').fill('wrong');await page.locator('#submitAccess').click();await page.locator('#accessError').filter({hasText:'incorrectos'}).waitFor();
 await login(player,'/casino');await page.locator('.nx-card').first().waitFor();assert.equal(await page.locator('.nx-card').count(),14);await noOverflow();await shot('casino-desktop');await shot('casino-desktop-full',true);
 await page.goto(base+'/');await page.locator('#accessForm').waitFor();await page.locator('#existingSession:not([hidden])').waitFor();assert.equal(new URL(page.url()).pathname,'/');
 await page.goto(base+'/admin');await page.waitForURL(base+'/casino');assert.equal((await json('/api/users')).status,403);assert.equal((await json('/api/wallet/transfer','post',{userId:2,action:'credit',amount:1})).status,403);
 await page.locator('#catalogSearch').fill('ruleta');assert.equal(await page.locator('.nx-card').count(),1);await page.locator('.nx-card').click();await page.locator('#categoryDialog[open]').waitFor();await page.locator('#categoryDialog .close').click();await page.locator('#catalogSearch').fill('nada-xyz');await page.locator('#clearSearch').click();assert.equal(await page.locator('.nx-card').count(),14);
 for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:844});await noOverflow();const nav=width<850?'.nx-bottomnav':'.nx-topnav';await page.locator(nav+' [data-category=sports]').click();assert.equal(await page.locator('.nx-card').count(),4);await page.locator(nav+' [data-category=all]').click();if(width===390){await page.goto(base+'/casino');await page.locator('.nx-card').first().waitFor();await shot('casino-mobile');await shot('casino-mobile-full',true)}}
 await page.locator('#logout').click();await page.waitForURL(base+'/');await page.goto(base+'/casino');await page.waitForURL(base+'/login');assert.equal((await json('/api/session')).body.user,null);
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/');await noOverflow();await shot('login-mobile',true);
 await page.setViewportSize({width:1440,height:1000});await login(admin,'/admin');await page.locator('.stat').first().waitFor();await page.goto(base+'/casino');await page.waitForURL(base+'/admin');await page.goto(base+'/');await page.locator('#accessForm').waitFor();await page.locator('#existingSession:not([hidden])').waitFor();
 await login(admin,'/admin');await page.locator('.stat').first().waitFor();await page.getByRole('button',{name:'+ Nuevo usuario'}).click();await page.locator('#createForm [name=username]').fill('prueba_creada');await page.locator('#createForm [name=password]').fill('Temporal!123');await page.locator('#createForm [name=full_name]').fill('Prueba de creación');await page.locator('#createForm .primary').click();await page.locator('#userRows').filter({hasText:'prueba_creada'}).waitFor();
 await page.locator('[data-view=wallet]').click();await page.locator('#walletUser').selectOption({label:'prueba_creada — Prueba de creación'});await page.locator('#walletAmount').fill('500');await page.getByRole('button',{name:'Confirmar movimiento'}).click();await page.locator('#walletMsg').filter({hasText:'Nuevo saldo: 500'}).waitFor();await page.locator('#walletAction').selectOption('debit');await page.locator('#walletAmount').fill('125');await page.getByRole('button',{name:'Confirmar movimiento'}).click();await page.locator('#walletMsg').filter({hasText:'Nuevo saldo: 375'}).waitFor();await page.locator('#walletAmount').fill('999');await page.getByRole('button',{name:'Confirmar movimiento'}).click();await page.locator('#walletMsg').filter({hasText:'Saldo insuficiente'}).waitFor();await page.locator('[data-view=ledger]').click();await page.locator('#ledgerRows').filter({hasText:'prueba_creada'}).waitFor();
 await page.locator('[data-view=media]').click();await page.getByRole('button',{name:'+ Subir banner'}).click();await page.locator('#bannerForm [name=title]').fill('Banner verificado');await page.locator('#bannerFile').setInputFiles(path.join(output,'login-mobile.png'));await page.locator('#bannerForm .primary').click();await page.locator('.media-name').filter({hasText:'Banner verificado'}).waitFor();
 const initial=(await json('/api/site')).body.settings;
 await page.locator('[data-view=settings]').click();await page.waitForFunction(()=>document.querySelector('#settingsForm [name=name]').value==='BRAVO');await page.locator('#settingsForm [name=tagline]').fill('Frase guardada desde el panel');await page.locator('#settingsForm [name=accent]').fill('#ffcc44');await page.locator('#settingsForm [name=sports]').uncheck();await page.locator('#settingsForm .primary').click();await page.locator('#settingsMsg').filter({hasText:'guardados'}).waitFor();
 await page.goto(base+'/preview');await page.locator('#previewNotice:not([hidden])').waitFor();await page.locator('#heroTitle').filter({hasText:'Banner verificado'}).waitFor();assert.equal(await page.locator('.nx-card').count(),10);assert.equal(await page.locator('.nx-topnav [data-category=sports]').isVisible(),false);
 const banners=(await json('/api/banners')).body.banners;for(const b of banners)assert.equal((await json('/api/banners/'+b.id,'delete')).status,200);
 await page.reload();await page.locator('#heroSubtitle').filter({hasText:'Frase guardada desde el panel'}).waitFor();assert.equal(await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--accent').trim()),'#ffcc44');
 await json('/api/site','put',{...initial,maintenance:true});await page.reload();await page.locator('#maintenance:not(.hidden)').waitFor();assert.equal(await page.locator('#lobbyContent').isVisible(),false);await json('/api/site','put',initial);
 await page.goto(base+'/admin');await page.locator('.stat').first().waitFor();await shot('admin-desktop');await page.setViewportSize({width:390,height:844});await noOverflow();await shot('admin-mobile',true);await page.getByRole('button',{name:'Salir',exact:true}).click();await page.waitForURL(base+'/login');await page.goto(base+'/admin');await page.waitForURL(base+'/login');
 await login(player,'/casino');await page.goto(base+'/');await page.locator('#closeExisting').click();await page.locator('#existingSession').waitFor({state:'hidden'});assert.equal((await json('/api/session')).body.user,null);await page.goto(base+'/casino');await page.waitForURL(base+'/login');
 // Blocking an authenticated player revokes page/API access immediately.
 await login(player,'/casino');const separate=await context.browser().newContext();await separate.request.post(base+'/api/login',{data:admin});const users=(await (await separate.request.get(base+'/api/users')).json()).users;const id=users.find(u=>u.username===player.username).id;await separate.request.patch(base+'/api/users/'+id,{form:{active:'false'}});await page.reload();await page.waitForURL(base+'/login');assert.equal((await json('/api/me/ledger')).status,401);await separate.close();
 assert.deepEqual(errors,[]);console.log('PASS: root always login with/without either session; real role redirects; protected aliases and encoded HTML; logout and blocked users; both demo accounts; idempotent additive seeding; create user; credit/debit/insufficient balance; ledger; banners; settings; maintenance; responsive 360/390/768/1440; no JS errors.');console.log('Evidence: '+output);
} catch(e){console.error(logs);throw e}finally{if(browser)await browser.close();server.kill();}
