import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const base=process.env.TEST_BASE_URL||'http://localhost:3100';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
async function login(user){await page.goto(base);await page.locator('[name=username]').fill(user);await page.locator('[name=password]').fill('demo1234');await page.locator('#submitAccess').click();await page.waitForURL(user==='jugador01'?'**/player.html':'**/master.html')}
async function overflow(){if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>[e.tagName,e.className,e.getBoundingClientRect().right]).slice(0,20)));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}
await page.goto(base+'/player.html');assert.equal(new URL(page.url()).pathname,'/');await page.goto(base+'/master.html');assert.equal(new URL(page.url()).pathname,'/');await page.screenshot({path:'/tmp/nexora-login.png',fullPage:true});
await page.locator('[name=username]').fill('wrong');await page.locator('[name=password]').fill('wrong');await page.locator('#submitAccess').click();await page.locator('#accessError').filter({hasText:'incorrectos'}).waitFor();
await login('jugador01');await page.locator('.nx-card').first().waitFor();assert.equal(await page.locator('.nx-card').count(),14);await overflow();await page.screenshot({path:'/tmp/nexora-desktop.png',fullPage:true});
await page.goto(base+'/master.html');await page.waitForURL('**/player.html');await page.locator('#catalogSearch').fill('Ruleta');assert.equal(await page.locator('.nx-card').count(),1);await page.locator('.nx-card').click();await page.locator('#categoryDialog[open]').waitFor();await page.locator('[data-close=categoryDialog]').click();await page.locator('#catalogSearch').fill('');
for(const width of [360,390,768]){await page.setViewportSize({width,height:844});await overflow();await page.locator('.nx-bottomnav [data-category=sports]').click();assert.equal(await page.locator('.nx-card').count(),4);await page.locator('.nx-bottomnav [data-category=all]').click();if(width===390){await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(300);await page.screenshot({path:'/tmp/nexora-mobile.png',fullPage:true})}}
await page.locator('#logout').click();await page.waitForURL(base+'/');await overflow();await page.screenshot({path:'/tmp/nexora-login-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});await login('masteradmin');await page.locator('.stat').first().waitFor();
await page.getByRole('button',{name:'+ Nuevo usuario'}).click();const username='ui'+Date.now();await page.locator('#createForm [name=username]').fill(username);await page.locator('#createForm [name=password]').fill('testpass123');await page.locator('#createForm [name=full_name]').fill('Usuario de prueba');await page.locator('#createForm .primary').click();await page.locator('#userRows').filter({hasText:username}).waitFor();
await page.locator('[data-view=wallet]').click();await page.locator('#walletUser').selectOption({label:username+' — Usuario de prueba'});await page.locator('#walletAmount').fill('500');await page.getByRole('button',{name:'Confirmar movimiento'}).click();await page.locator('#walletMsg').filter({hasText:'Nuevo saldo: 500'}).waitFor();await page.locator('#walletAction').selectOption('debit');await page.locator('#walletAmount').fill('125');await page.getByRole('button',{name:'Confirmar movimiento'}).click();await page.locator('#walletMsg').filter({hasText:'Nuevo saldo: 375'}).waitFor();
await page.locator('[data-view=media]').click();await page.getByRole('button',{name:'+ Subir banner'}).click();await page.locator('#bannerForm [name=title]').fill('Portada de prueba');await page.locator('#bannerFile').setInputFiles('/tmp/nexora-login-mobile.png');await page.locator('#bannerForm .primary').click();await page.locator('.media-name').filter({hasText:'Portada de prueba'}).waitFor();
const initial=(await (await page.request.get(base+'/api/site')).json()).settings;
await page.locator('[data-view=settings]').click();await page.waitForFunction(()=>document.querySelector('#settingsForm [name=name]').value==='NEXORA');await page.locator('#settingsForm [name=tagline]').fill('Frase desde administración');await page.locator('#settingsForm [name=accent]').fill('#ffcc44');await page.locator('#settingsForm [name=sports]').uncheck();await page.locator('#settingsForm .primary').click();await page.locator('#settingsMsg').filter({hasText:'guardados'}).waitFor();
await page.goto(base+'/player.html');await page.locator('#heroTitle').filter({hasText:'Portada de prueba'}).waitFor();assert.equal(await page.locator('.nx-card').count(),10);assert.equal(await page.locator('.nx-topnav [data-category=sports]').isVisible(),false);assert.equal(await page.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--accent').trim()),'#ffcc44');
const banners=(await (await page.request.get(base+'/api/banners')).json()).banners;for(const b of banners)await page.request.delete(base+'/api/banners/'+b.id);await page.reload();await page.locator('#heroSubtitle').filter({hasText:'Frase desde administración'}).waitFor();
await page.request.put(base+'/api/site',{data:{...initial,maintenance:true}});await page.reload();await page.locator('#maintenance:not(.hidden)').waitFor();assert.equal(await page.locator('#lobbyContent').isVisible(),false);await page.request.put(base+'/api/site',{data:initial});
await page.goto(base+'/master.html');await page.locator('.stat').first().waitFor();await page.screenshot({path:'/tmp/nexora-admin.png',fullPage:true});await page.setViewportSize({width:390,height:844});await overflow();await page.screenshot({path:'/tmp/nexora-admin-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: login, role routing, guest guards, responsive layouts, catalog search, categories, creation, wallet, banners, settings, maintenance, no JS errors.');await browser.close();
